/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FullLoading: typeof import('./src/components/FullLoading.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LangSwitcher: typeof import('./src/components/LangSwitcher.vue')['default']
    NutAnimate: typeof import('@nutui/nutui')['Animate']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutIndicator: typeof import('@nutui/nutui')['Indicator']
    NutLoading: typeof import('@nutui/nutui')['Loading']
    NutOverlay: typeof import('@nutui/nutui')['Overlay']
    NutPopover: typeof import('@nutui/nutui')['Popover']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
